import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import MenuIcon from '@mui/icons-material/Menu';
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Divider from '@mui/material/Divider';
import Drawer from '@mui/material/Drawer';
import IconButton from '@mui/material/IconButton';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemText from '@mui/material/ListItemText';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Head from 'next/head';
import Image from 'next/image';
import * as React from 'react';

import navItems from '../data/nav';
import logo from '../public/logo-full.svg';
import Link from './Link';

const pageWidth = 1000;
const drawerWidth = 240;

function Logo() {
  return (
    <Button
      href='https://www.dlford.io'
      component={Link}
      width={119}
      height={44}
    >
      <Image
        src={logo}
        layout='fill'
      />
    </Button>
  );
}

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [drawerOpen, setDrawerOpen] = React.useState(false);

  const handleDrawerToggle = () => {
    setDrawerOpen(!drawerOpen);
  };

  const drawer = (
    <Box
      onClick={handleDrawerToggle}
      sx={{ textAlign: 'center' }}
    >
      <Typography
        variant='h6'
        sx={{ my: 2 }}
      >
        Utilities
      </Typography>
      <Divider />
      <List>
        {navItems.map(({ title, href, Icon }) => (
          <ListItem
            key={href}
            disablePadding
          >
            <ListItemButton
              href={href}
              component={Link}
              sx={{ textAlign: 'center' }}
            >
              <Icon />
              <ListItemText primary={title} />
            </ListItemButton>
          </ListItem>
        ))}
      </List>
    </Box>
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>

      <Box
        sx={{
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100%',
        }}
      >
        <Box sx={{ display: 'flex' }}>
          <AppBar>
            <Toolbar
              sx={{
                width: pageWidth,
                maxWidth: '100%',
                margin: '0 auto',
              }}
            >
              <Typography
                variant='h6'
                component='div'
                sx={{
                  flexGrow: 1,
                }}
              >
                <Logo />
              </Typography>
              <IconButton
                color='inherit'
                aria-label='open drawer'
                edge='start'
                onClick={handleDrawerToggle}
              >
                <MenuIcon />
              </IconButton>
            </Toolbar>
          </AppBar>
          <Box component='nav'>
            <Drawer
              variant='temporary'
              anchor='right'
              open={drawerOpen}
              onClose={handleDrawerToggle}
              ModalProps={{
                keepMounted: true, // Better open performance on mobile.
              }}
              sx={{
                '& .MuiDrawer-paper': {
                  boxSizing: 'border-box',
                  width: drawerWidth,
                },
              }}
            >
              {drawer}
            </Drawer>
          </Box>
          <Box
            component='main'
            sx={{
              width: pageWidth,
              maxWidth: '100%',
              margin: '0 auto',
            }}
          >
            <Toolbar />
            {children}
          </Box>
        </Box>
        <Box
          component='footer'
          sx={{
            marginTop: 'auto',
            marginBottom: 0,
            p: 3,
            display: 'flex',
            justifyContent: 'center',
          }}
        >
          <Link
            href='https://www.dlford.io'
            rel='noopener noreferrer'
            target='_blank'
          >
            dlford &copy; {new Date().getFullYear()}
          </Link>
        </Box>
      </Box>
    </>
  );
}
